pod 'BlackBerryDynamics', :podspec => 'https://software.download.blackberry.com/repository/framework/dynamics/ios/BlackBerryDynamics.podspec'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'RN64' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'RN64Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #
  # Flipper cannot be used together with BlackBerry Dynamics SDK for React Native on iOS
  # in debug configuration as it disables some BlackBerry Dynamics functionality
  # related to secure networking.
  # use_flipper!()

  post_install do |installer|
		system("node ../node_modules/BlackBerry-Dynamics-for-React-Native-Base/scripts/updatePods.js")
   react_native_post_install(installer)
  end
end